### ISSUE TITLE
Some posts show in the wrong order

### ISSUE THREAD

**Issue by Gravechapa** [NC22/KellyC-JoyReactor#1]
Like [this one](https://old.reactor.cc/post/5688476).
I think the issue may be that the reactor API doesn't enforce sequential numbering of attribute insert IDs.
Plugin version is 1.2.8.1.
![Screenshot_20231116_133506](https://github.com/NC22/KellyC-JoyReactor/assets/13240067/3becb152-efd4-4e2d-8ffc-5440b194c017)

**Comment by NC22** [comment]
Спасибо. Как одобрят новую версию (1.2.8.2), будет учтен этот параметр

**Comment by Gravechapa** [comment]
Фикс работает, спасибо.
